export default {
    A: { ada: "Ada", asciidoc: "AsciiDoc", awk: "Awk", autohotkey: "AutoHotkey" },
    B: { bash: "Bash" },
    C: { c: "c", clj: "Clojure", coffeescript: "CoffeeScript", cpp: "C++", crystal: "Crystal", csharp: "C#", cs: "C#", css: "CSS" },
    D: { d: "D", dart: "Dart", delphi: "Delphi", diff: "Diff", dockerfile: "Dockerfile" },
    E: { elixir: "Elixir", elm: "Elm", erl: "Erlang" },
    F: { fix: "Fix", fs: "F#", fsharp: "F#" },
    G: { go: "Go", glsl: "GLSL", graphql: "GraphQL", groovy: "Groovy" },
    H: { hs: "Haskell", html: "HTML/XML" },
    I: { ini: "INI" },
    J: { java: "Java", js: "JavaScript", json: "JSON", julia: "Julia" },
    K: { kt: "Kotlin" },
    L: { latex: "LaTeX", less: "Less", lisp: "Lisp", lua: "Lua" },
    M: { markdown: "Markdown", matlab: "Matlab", md: "Markdown", mk: "Makefile", ml: "OCaml" },
    N: { nginx: "Nginx", nim: "Nim" },
    O: { ml: "OCaml" },
    P: { perl: "Perl", php: "PHP", powershell: "Powershell", prolog: "Prolog", ps: "PowerShell", py: "Python" },
    R: { pl: "Raku", r: "R", rs: "Rust", ruby: "Ruby" },
    S: { sas: "SAS", scala: "Scala", scheme: "Scheme", scss: "SCSS", sql: "SQL", switf: "Swift" },
    T: { tcl: "Tcl", tex: "TeX", ts: "TypeScript" },
    V: { vbnet: "VB.NET", vhdl: "VHDL" },
    X: { xl: "Excel", xml: "XML" },
    Y: { yaml: "YAML", yml: "YAML" },
    Z: { zsh: "ZSH" }
} as const;
